import { UserProfile } from "./types";

export const defaultProfile: UserProfile = {
  personalInfo: {
    fullName: "Md. Abu Nayeem",
    email: "nayemahmed197@gmail.com",
    phone: "+880 1938-132865",
    nationality: "Bangladesh",
    address: "Moshipur, Shahjadpur, Sirajganj 6770, Bangladesh",
    title: "Prospective Graduate Scholar in Hospitality & Tourism Management",
    linkedin: "",
    portfolio: "",
  },
  profileSummary:
    "Marketing- and operations-trained professional with 3.5+ years of applied experience in the aviation and travel industry, complemented by grassroots community-research experience in the development sector. Currently manages reservations, client relationships, service quality, and promotional campaigns for a major international airline — direct, day-to-day exposure to the guest experience, service delivery, and destination-facing side of the travel and hospitality value chain. Seeking to build advanced graduate-level expertise in Hospitality & Tourism Management, connecting commercial industry practice with rigorous academic research on destination management, service quality, and sustainable tourism development, with the long-term goal of contributing to the professionalism and growth of Bangladesh's tourism and hospitality sector.",
  education: [
    {
      id: "edu-1",
      degree: "Master of Business Administration (MBA)",
      field: "Marketing",
      institution: "University of Rajshahi",
      location: "Bangladesh",
      startDate: "2020",
      endDate: "2021",
      gpa: "3.79/4.00",
      relevantCoursework: [
        "Strategic Management",
        "Consumer Behaviour",
        "International Marketing",
        "Market Research Methods",
        "Organisational Behaviour",
        "Financial Management",
        "Business Statistics",
      ],
      achievements: [
        "Authored independent research paper on consumer behaviour in Bangladesh's emerging market",
        "Full research lifecycle: problem formulation, literature review, primary data collection (200+ respondents), mixed-methods analysis",
        "Supervised by Prof. Dr. Md. Faridul Islam, Vice-Chancellor, University of Rajshahi",
      ],
    },
    {
      id: "edu-2",
      degree: "Bachelor of Business Administration (BBA)",
      field: "Marketing",
      institution: "National University",
      location: "Bangladesh",
      startDate: "2014",
      endDate: "2018",
      gpa: "3.16/4.00",
      relevantCoursework: [],
      achievements: [],
    },
    {
      id: "edu-3",
      degree: "Higher Secondary Certificate (HSC)",
      field: "Commerce",
      institution: "Shahid Akbar Ali Science & Technology College",
      location: "Bangladesh",
      startDate: "2013",
      endDate: "2014",
      gpa: "4.50/5.00",
      relevantCoursework: [],
      achievements: [],
    },
    {
      id: "edu-4",
      degree: "Secondary School Certificate (SSC)",
      field: "Science",
      institution: "Talgachi A.I. High School",
      location: "Bangladesh",
      startDate: "2010",
      endDate: "2011",
      gpa: "4.19/5.00",
      relevantCoursework: [],
      achievements: [],
    },
  ],
  workExperience: [
    {
      id: "work-1",
      position: "Sales, Reservation & Ticketing — Central Reservation",
      company: "US-Bangla Airlines",
      location: "Dhaka, Bangladesh",
      startDate: "Mar 2023",
      endDate: "Present",
      current: true,
      responsibilities: [
        "Applied travel-industry and service-management competencies — reservation systems (GDS: Galileo, Sabre), client relationship management, and service quality monitoring",
        "Managed a portfolio of 50+ high-value corporate clients with 95% retention rate",
        "Built quantitative performance dashboards tracking 15+ KPIs for evidence-based decisions",
        "Trained and led groups of new trainees and cross-functional teams of 5-10 members",
      ],
      achievements: [
        "Co-created 8+ promotional and marketing campaigns generating BDT 15+ crore in incremental revenue",
        "Identified 12+ service-delivery inefficiencies, improved operational efficiency by 25% and customer satisfaction by 18%",
        "Achieved 95% client retention rate through relationship-based stakeholder engagement",
      ],
    },
    {
      id: "work-2",
      position: "Community Research & Programme Intern",
      company: "RRF (NGO)",
      location: "Jessore, Bangladesh",
      startDate: "Nov 2017",
      endDate: "May 2018",
      current: false,
      responsibilities: [
        "Conducted community-based needs assessments and participatory research across 8+ rural communities",
        "Designed survey instruments and collected primary data from 200+ respondents",
        "Produced evidence-based policy reports",
      ],
      achievements: [
        "Reached 500+ households across 8+ rural communities",
        "Produced 3 evidence-based policy reports informing funding decisions for 2 community development projects",
        "Co-designed 4 process innovations with community stakeholders",
      ],
    },
  ],
  skills: [
    { id: "skill-1", name: "Guest experience and service quality management", category: "Hospitality & Tourism", level: "Advanced" },
    { id: "skill-2", name: "GDS reservation systems (Galileo, Sabre)", category: "Hospitality & Tourism", level: "Advanced" },
    { id: "skill-3", name: "Destination and travel-product marketing", category: "Hospitality & Tourism", level: "Advanced" },
    { id: "skill-4", name: "Client relationship management", category: "Hospitality & Tourism", level: "Advanced" },
    { id: "skill-5", name: "Event and MICE coordination", category: "Hospitality & Tourism", level: "Intermediate" },
    { id: "skill-6", name: "Revenue management", category: "Hospitality & Tourism", level: "Intermediate" },
    { id: "skill-7", name: "Primary data collection and survey design", category: "Research & Academic", level: "Advanced" },
    { id: "skill-8", name: "Quantitative and qualitative analysis", category: "Research & Academic", level: "Advanced" },
    { id: "skill-9", name: "Literature review and academic writing", category: "Research & Academic", level: "Advanced" },
    { id: "skill-10", name: "SPSS", category: "Research & Academic", level: "Intermediate" },
    { id: "skill-11", name: "Strategic planning and execution", category: "Management & Leadership", level: "Advanced" },
    { id: "skill-12", name: "Team training and leadership (5-10 members)", category: "Management & Leadership", level: "Advanced" },
    { id: "skill-13", name: "MS Office Suite (Advanced)", category: "Digital & Technical", level: "Advanced" },
    { id: "skill-14", name: "Performance dashboards and KPI tracking", category: "Digital & Technical", level: "Advanced" },
    { id: "skill-15", name: "Graphic design", category: "Digital & Technical", level: "Intermediate" },
    { id: "skill-16", name: "Web design and development", category: "Digital & Technical", level: "Intermediate" },
    { id: "skill-17", name: "Cross-cultural and intercultural communication", category: "Interpersonal", level: "Advanced" },
    { id: "skill-18", name: "Public speaking and presentations", category: "Interpersonal", level: "Advanced" },
    { id: "skill-19", name: "Community engagement", category: "Interpersonal", level: "Advanced" },
  ],
  languages: [
    { id: "lang-1", name: "Bengali", proficiency: "Native speaker", cefrLevel: "C2" },
    { id: "lang-2", name: "English", proficiency: "Proficient", cefrLevel: "C1" },
  ],
  researchInterests: [
    { id: "ri-1", topic: "Hospitality and tourism service quality, guest experience management, and customer satisfaction in emerging markets" },
    { id: "ri-2", topic: "Aviation–tourism linkages: air connectivity, destination accessibility, and travel demand in South Asia" },
    { id: "ri-3", topic: "Sustainable and community-based tourism development, with a focus on Bangladesh's cultural heritage and eco-tourism assets" },
    { id: "ri-4", topic: "Destination marketing, branding, and stakeholder coordination across the public and private tourism and hospitality sectors" },
    { id: "ri-5", topic: "Hotel and hospitality operations management, revenue management, and MICE coordination" },
    { id: "ri-6", topic: "Digital transformation in tourism and hospitality: data-driven service management and customer analytics" },
  ],
  certifications: [
    {
      id: "cert-1",
      name: "Duke of Edinburgh's International Award",
      issuer: "Cantonment College",
      date: "Nov 2016 – Apr 2017",
      description: "Completed all four components (Volunteering, Skill, Physical, Expedition) within a programme active in 144+ countries.",
    },
    {
      id: "cert-2",
      name: "Active Citizens Youth Leadership Programme",
      issuer: "RRF / British Council affiliate",
      date: "2015",
      description: "Competitively selected; independently designed and delivered a community-based initiative benefiting 150+ community members.",
    },
    {
      id: "cert-3",
      name: "Web Design & Development",
      issuer: "RRF, Jessore",
      date: "Nov 2017 – May 2018",
      description: "6-month certificate programme in web design and development.",
    },
    {
      id: "cert-4",
      name: "Graphic Design",
      issuer: "Bangladesh Computer Council",
      date: "Oct 2017 – Mar 2018",
      description: "6-month certificate programme in graphic design.",
    },
  ],
  references: [
    {
      id: "ref-1",
      name: "Prof. Dr. Md. Faridul Islam",
      title: "Vice-Chancellor & Professor, Department of Marketing",
      institution: "University of Rajshahi",
      email: "faridulmkt@ru.ac.bd",
      relation: "Academic Supervisor (MBA)",
    },
    {
      id: "ref-2",
      name: "Rudrendu Ray",
      title: "Associate Professor, Department of Marketing",
      institution: "University of Rajshahi",
      email: "rudra@ru.ac.bd",
      relation: "Academic / MBA Faculty",
    },
  ],
};
